name: app
description: movie app

publish_to: 'none' 

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.5 <3.3.6'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.2
  flutter_easyloading: 
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^4.0.4
  injectable: ^2.1.1
  json_annotation: ^4.7.0
  provider:
  dio:
  shared_preferences: ^2.0.15
  flutter_svg: ^2.0.6

dev_dependencies:
  build_runner: ^2.2.0
  flutter_gen_runner:
  flutter_lints:
  freezed: ^2.0.5
  injectable_generator: ^2.1.5
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true